name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
      
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v3

      - uses: Platane/snk@v3
        with:
          github_user_name: pedro1801
          outputs: output/snake.svg
          
      - uses: Platane/snk@v3
        with:
          github_user_name: pedro1801
          outputs: output/snake-dark.svg
          theme: github-dark 

      - name: Commit and Push snake files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          # Adiciona os dois arquivos
          git add output/snake.svg
          git add output/snake-dark.svg
          if git diff --staged --quiet; then
            echo "Nenhuma mudança na animação, commit não é necessário."
          else
            git commit -m "feat: update snake contribution grid (light/dark)"
            git push
          fi
